# Window setup - ../root/views.py
APP_NAME = "App de prueba"
WIDTH = 800
HEIGHT = 400

# get attributs from Book model - ../books/models/models.py
FIRST_MEMBER_POS = 0
ATTR_POS = 1

# Get attributs position
TITLE_POS = 0
AUTHOR_POS = 1
SYNOPSIS_POS = 2
GENRE_POS = 3
PUBLISHER_POS = 4
ORIGINAL_LANGUAGE_POS = 5
BOOK_LANGUAGE_POS = 6
NUMBER_OF_PAGES_POS = 7
CURRENT_PAGE_POS = 8
CREATED_DATE_POS = 9
PURCHASE_DATE_POS = 10
PUBLICATION_DATE_POS = 11
READING_DATE_POS = 12
ALREADY_DATE_POS = 13
IS_CURRENT_BOOK_POS = 14
